### ISSUE TITLE
Inertia / Easing on DragEnd

### ISSUE THREAD

**Issue by harrison-drift** [its2easy/animate-images#2]
Would be neat if we could add an inertia or easing function so the sequence caries on gradually slowing down as it comes to a stop after dragging. For the best "feel" this might need to keep track of the drag speed.

I've been trying to figure this out but just can't get it. Any help would be appreciated!

**Comment by its2easy** [comment]
I made a basic [example](https://codepen.io/its2easy/pen/dymbgpK) with easing function, but you should probably change the calculation of `inertiaTime` and `framesToPlay` variables. Also my version uses timestamps from the last drag events to measure speed, and I think the right way is to setup another mousemove/touchmove handler that will measure the speed after drag start.

**Comment by its2easy** [comment]
Hi @Harry-Harrison, are you still working on the inertia or I could close the issue?

**Comment by harrison-drift** [comment]
Hey sorry, feel free to close and thanks for your guidance on it! I've not had time to create my own attempt, but I like the approach you took!
