### ISSUE TITLE
Seems to move faster when dragging from right-to-left than left-to-right

### ISSUE THREAD

**Issue by harrison-drift** [its2easy/animate-images#3]
Having a hard time proving this mathematically, but when testing with images with a fixed centre point you can see it quite well. Seems like it's maybe 1.5 speed?

**Comment by its2easy** [comment]
[https://codepen.io/its2easy/pen/gOeOpjN](https://codepen.io/its2easy/pen/gOeOpjN)
From 5 to 1 and from 5 to 9 seem like the speed is the same.
Maybe your animation was rendered with a non linear speed?

**Comment by its2easy** [comment]
In 2.3.0 I fixed a bug that caused unnecessary frame changes to the left. The changes were mostly zero length, but maybe in your case they were noticeable, so new version should fix it.

**Comment by harrison-drift** [comment]
Oh amazing! Thank you for looking into it more. I was hoping to get a demo together to see if I could really hone in on where it was happening but I reckon you beat me to it.

Will give this a shot soon. 🙂
