### ISSUE TITLE
[feature request] Animate on Scroll

### ISSUE THREAD

**Issue by laurensV** [its2easy/animate-images#4]
Would it be difficult to add a feature where we could animate the image frames on scroll? Something similar to this demo from canvas-scroll-clip: https://m5kr1pka.github.io/canvas-scroll-clip/?path=/story/canvas-scroll-clip--default ?

**Comment by its2easy** [comment]
I could add a simple version, but it will only cover a very small number of use cases. If I add a complex one, then the size of the library can increase significantly, and it will most likely be buggy. So I recommend using existing third party libraries that trigger callbacks on scroll, like [GSAP ScrollTrigger](https://greensock.com/scrolltrigger/), [scrollama](https://github.com/russellgoldenberg/scrollama), [enter-view](https://github.com/russellgoldenberg/enter-view) or implement your own with intersection observer.
BTW, you can see how animate-images + scrolltrigger works [here](https://aorion.aero/aorion-heli-e/#battery)
