### ISSUE TITLE
[feature request] Responsiveness based on height

### ISSUE THREAD

**Issue by laurensV** [its2easy/animate-images#5]
Right now you can only achieve responsiveness by leaving the height empty and setting the width. Would be great if the opposite would also be possible: leaving the width empty and setting the height.

**Comment by its2easy** [comment]
What are the use cases with auto width? When `height: auto`, you can have canvas height more than screen height, and it will just add vertical scroll, which is ok. With `width: auto` the canvas width could be larger than screen width and this will add horizontal scroll, which is unwanted in most cases, or part of the canvas will be hidden offscreen.

**Comment by its2easy** [comment]
I added this in 2.3.0 anyway. It works with new `responsiveAspect` option.
