### ISSUE TITLE
Minified build files on npm are not working

### ISSUE THREAD

**Issue by laurensV** [its2easy/animate-images#6]
In production, where I am using the minified version of esm (https://cdn.jsdelivr.net/npm/@its2easy/animate-images/build/animate-images.esm.min.js) I get the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'pageX')
```
The minified version both defines a function i (`function i(t,i)`) and replaces the `touches` variable (https://github.com/its2easy/animate-images/blob/master/src/DragInput.js#L69) also with the letter `i`, causing it to conflict and causing the error above.

**Comment by laurensV** [comment]
The minified UMD version also give the same error (although there `i` seems to be defined as a class already, not a function)

**Comment by its2easy** [comment]
@laurensV How do you get this error? 
[Demo](https://codepen.io/its2easy/pen/powQJmd) works with latest [min umd](https://unpkg.com/@its2easy/animate-images@2.3.0/build/animate-images.umd.min.js), seems ok

**Comment by laurensV** [comment]
Ah its seems it has something todo with vite/rollup that is trying to optimize dependencies being used for nuxt3 (vue), that is deleting the `let i;` line from your minified version, causing it to error. Nothing todo with your build files, sorry!
